version: '3.8'

services:
  client:
    container_name: vt-client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: always

  backend:
    container_name: vt-server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app
      - /app/node_modules
      - ./server/data:/app/data
    environment:
      - NODE_ENV=production
    restart: always